### PR TITLE
Make style to be a decorator

### PR DESCRIPTION
**Pull request by saroad2**
Unfortunately, I was unable to add the auto-completion for the `__init__` function, since its parameters are dynamic.

But all the other stuff works :)

### CODE REVIEW

**Comment by saroad2** [comment]
fixes #11

**Comment by saroad2** [comment]
I took another look at my code and so that all the other functions such as copy, items, reapply, etc. are not auto-completed now. So we got the completion of the validated properties at the expense of the functionalities of the class...

There are 2 ways we can "solve it"

1. Decide that the completion of the properties is more important than the completion of the methods and leave the code in this pull request as it is
2. Create a chimera of the previous design and the new suggested design as the following:
```python
class Pack(BaseStyle):
    display: str = validated_property(choices=DISPLAY_CHOICES, initial=PACK)
    visibility: str = validated_property(choices=VISIBILITY_CHOICES, initial=VISIBLE)
    direction: str = validated_property(choices=DIRECTION_CHOICES, initial=ROW)
    alignment: str = validated_property(choices=ALIGNMENT_CHOICES)

    padding_top: int = validated_property(choices=PADDING_CHOICES, initial=0)
    padding_right: int = validated_property(choices=PADDING_CHOICES, initial=0)
    padding_bottom: int = validated_property(choices=PADDING_CHOICES, initial=0)
    padding_left: int = validated_property(choices=PADDING_CHOICES, initial=0)
```

In that way, the methods are inherited from `BaseStyle` and the properties are loaded from `validated_property`

Personally, I like the first one better because once we deprecate python 3.5 support, we could wrap the actual `dataclass` decorator presented in python 3.6 (for python 3.6 you can install it using pip and for python 3.7 it's part of the built-in libraries) to gain the same functionalities (the `style` would call `dataclass` and `validated_property` would call `field`)

**Comment by saroad2** [comment]
As I was thinking a little bit more about it I came to the conclusion that the best thing to do is to wait until you decide that the BeeWare platform do not support Python 3.5 anymore and than use the [dataclass](https://docs.python.org/3/library/dataclasses.html) module.
Most IDEs have a special handling for dataclasses completion, so that would solve all our problems.
You can close the PR.

**Comment by freakboy3742** [comment]
Fair enough; I'll close for now.

Python 3.5 becomes EOL in October this year (2020), so that's the earliest we could deprecate Python 3.5. The biggest complication to deprecating that soon is that Ubuntu 16.04 is supported until 2024 - and Python 3.5 is the default Python there.

**Pull request closed without merging**
